(function(global){
'use strict';
const bucket='mimo-media',prefix='https://zhhgiwqehwuwzxnqbnth.supabase.co/storage/v1/object/authenticated/'+bucket+'/',MAX_IMAGE=20*1024*1024,MAX_VIDEO=30*1024*1024;
function reference(path){return prefix+path;}
function pathOf(url){if(typeof url!=='string'||!url.startsWith(prefix))return null;const p=url.slice(prefix.length);return /^[0-9a-f-]{36}\/(posts\/[0-9a-f-]{36}\/(?:[1-6]\.jpg|reel\.(?:mp4|mov|webm))|chats\/[0-9a-f-]{36}\/[0-9a-f-]{36}\.jpg)$/.test(p)?p:null;}
// Mobile album providers can omit MIME or use a container alias.
// Extension fallback is limited to missing MIME; contradictory types stay rejected.
function videoType(file){const type=String(file?.type||'').toLowerCase();const aliases={'video/mp4':'video/mp4','video/x-m4v':'video/mp4','video/quicktime':'video/quicktime','video/x-quicktime':'video/quicktime','video/mov':'video/quicktime','video/webm':'video/webm'};if(aliases[type])return aliases[type];if(type)return null;const ext=String(file?.name||'').toLowerCase().split('.').pop();return {mp4:'video/mp4',m4v:'video/mp4',mov:'video/quicktime',webm:'video/webm'}[ext]||null;}
function videoExtension(file){return {'video/mp4':'mp4','video/quicktime':'mov','video/webm':'webm'}[videoType(file)]||null;}
function validate(file,video=false){const types=video?['video/mp4','video/webm','video/quicktime']:['image/jpeg','image/png','image/webp','image/heic','image/heif'];if(!file||!(video?videoType(file):types.includes(file.type))||file.size<=0||file.size>(video?MAX_VIDEO:MAX_IMAGE))throw Error(video?'Choose an MP4, MOV or WebM video up to 30 MB.':'Choose a JPEG, PNG, WebP or device-supported HEIC photo up to 20 MB.');}
async function image(file){validate(file);const url=URL.createObjectURL(file);try{const img=new Image();await new Promise((resolve,reject)=>{img.onload=resolve;img.onerror=()=>reject(Error('This photo cannot be decoded. Export it as JPEG and retry.'));img.src=url;});const w=img.naturalWidth,h=img.naturalHeight;if(!w||!h||w*h>50000000)throw Error('Photo dimensions are too large.');const scale=Math.min(1,1600/Math.max(w,h)),canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(w*scale));canvas.height=Math.max(1,Math.round(h*scale));const ctx=canvas.getContext('2d');ctx.fillStyle='#fff';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.drawImage(img,0,0,canvas.width,canvas.height);const blob=await new Promise(resolve=>canvas.toBlob(resolve,'image/jpeg',.82));if(!blob||blob.size>3145728)throw Error('Compressed photo exceeds 3 MB. Choose a smaller photo.');return blob;}finally{URL.revokeObjectURL(url);}}
async function video(file){validate(file,true);const url=URL.createObjectURL(file),node=document.createElement('video');let timeout;try{node.preload='metadata';node.playsInline=true;node.muted=true;await new Promise((resolve,reject)=>{timeout=setTimeout(()=>reject(Error('Unable to read video. Try a shorter MP4.')),15000);node.onloadedmetadata=()=>{clearTimeout(timeout);resolve();};node.onerror=()=>{clearTimeout(timeout);reject(Error('This device cannot decode this video. Export as MP4 and retry.'));};node.src=url;node.load();});if(!Number.isFinite(node.duration)||node.duration<=0)throw Error('Unable to read video duration. Export as MP4 and retry.');if(node.duration>90)throw Error('Choose a video up to 90 seconds.');return file;}finally{clearTimeout(timeout);node.onloadedmetadata=node.onerror=null;node.removeAttribute('src');node.load();URL.revokeObjectURL(url);}}

function attempt(){return {id:crypto.randomUUID(),done:new Set(),blobs:new Map()};}
async function upload(client,state,path,file,isVideo=false,alive=()=>true,status=()=>{}){if(!alive())throw Error('Session changed.');if(!state.done.has(path)){if(!state.blobs.has(path))state.blobs.set(path,isVideo?await video(file):await image(file));if(!alive())throw Error('Session changed.');status('Uploading…');const blob=state.blobs.get(path),{error}=await client.storage.from(bucket).upload(path,blob,{contentType:isVideo?videoType(file):'image/jpeg',upsert:false,cacheControl:'300'});if(error&&String(error.statusCode)!=='409'&&!/already exists|duplicate/i.test(error.message||''))throw Error(error.message||'Upload failed. Retry when connected.');if(!alive())throw Error('Session changed.');state.done.add(path);}return reference(path);}
function resolver(client,alive=()=>true){let disposed=false;const nodes=new Map();async function sign(node,value,attribute='src'){const path=pathOf(value);if(!path){node.setAttribute(attribute,value);return;}let attributes=nodes.get(node);if(!attributes){attributes=new Map();nodes.set(node,attributes);}const state={path,attribute,version:0};attributes.set(attribute,state);await refresh(node,state);}
 async function refresh(node,state){const version=++state.version;try{const {data,error}=await client.storage.from(bucket).createSignedUrl(state.path,300);if(error||!data?.signedUrl)throw Error('Media unavailable');if(disposed||!alive()||nodes.get(node)?.get(state.attribute)!==state||state.version!==version)return;node.setAttribute(state.attribute,data.signedUrl);node.removeAttribute('data-media-error');}catch{if(!disposed&&alive()&&nodes.get(node)?.get(state.attribute)===state&&state.version===version){node.removeAttribute(state.attribute);node.setAttribute('data-media-error','true');if(node.tagName==='IMG')node.alt='Photo unavailable. Refresh to retry.';}}}
 function renew(){if(disposed||!alive()||document.hidden)return;for(const [node,attributes] of nodes){if(!node.isConnected){nodes.delete(node);continue;}for(const state of attributes.values()){if(node.tagName==='VIDEO'&&state.attribute==='src'&&!node.paused)continue;refresh(node,state);}}}
 const timer=setInterval(renew,120000);document.addEventListener('visibilitychange',renew);return {sign,renew,dispose(){disposed=true;clearInterval(timer);document.removeEventListener('visibilitychange',renew);for(const [node,attributes]of nodes)for(const state of attributes.values())node.removeAttribute(state.attribute);nodes.clear();}};
}
function display(node,url,attribute='src'){if(global.mimoMediaResolver)global.mimoMediaResolver.sign(node,url,attribute);else if(!pathOf(url))node.setAttribute(attribute,url);}
function selection(input,preview,{video:asVideo=false,max=6,onChange=()=>{},canChange=()=>true}={}){let files=[],urls=[];function clear(){for(const video of preview.querySelectorAll('video'))video.pause();for(const url of urls)URL.revokeObjectURL(url);urls=[];files=[];input.value='';preview.replaceChildren();}input.onchange=()=>{if(!canChange()){input.value='';return;}const chosen=Array.from(input.files||[]);try{if(chosen.length>max)throw Error('Choose up to '+max+' files.');chosen.forEach(f=>validate(f,asVideo));clear();files=chosen;draw();onChange();}catch(error){input.value='';onChange(error);}};function draw(){preview.replaceChildren();for(let i=0;i<files.length;i++){const card=document.createElement('div');card.className='upload-preview';const url=URL.createObjectURL(files[i]);urls.push(url);const img=document.createElement(asVideo?'video':'img');img.src=url;img.alt='Selected photo';if(asVideo){img.controls=true;img.playsInline=true;img.preload='metadata';}const remove=document.createElement('button');remove.type='button';remove.textContent='×';remove.setAttribute('aria-label','Remove selected file');remove.onclick=()=>{if(!canChange())return;files.splice(i,1);for(const u of urls)URL.revokeObjectURL(u);urls=[];draw();onChange();};card.append(img,remove);preview.append(card);}}return {files:()=>files.slice(),clear,dispose:clear};}
global.MimoMedia={videoType,videoExtension,bucket,reference,pathOf,validate,image,video,attempt,upload,resolver,display,selection};
})(window);
