(function(global){
'use strict';
const paths={search:'M21 21l-5-5M18 10a8 8 0 1 1-16 0 8 8 0 0 1 16 0Z',edit:'M12 20H4V4h8M16 3l5 5-10 10-5 1 1-5 9-11Z',back:'m15 4-8 8 8 8',phone:'M6 3H3v4c0 8 6 14 14 14h4v-3l-5-3-2 2a13 13 0 0 1-7-7l2-2-3-5Z',video:'M3 5h12v14H3V5ZM15 9l6-4v14l-6-4',more:'M5 12h.01M12 12h.01M19 12h.01',send:'m22 2-7 20-4-9-9-4 20-7ZM22 2 11 13',smile:'M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0ZM8 9h.01M16 9h.01M8 14c2 3 6 3 8 0',plus:'M12 5v14M5 12h14',home:'m3 10 9-7 9 7v11h-6v-7H9v7H3V10Z',chat:'M21 11a9 9 0 0 1-9 9H5l-3 2V11a9 9 0 0 1 19 0Z',grid:'M3 3h6v6H3zM15 3h6v6h-6zM3 15h6v6H3zM15 15h6v6h-6z',user:'M20 21v-2a8 8 0 0 0-16 0v2M16 7a4 4 0 1 1-8 0 4 4 0 0 1 8 0Z',refresh:'M20 7a9 9 0 1 0 1 9M20 2v6h-6'};
function icon(d,name){const svg=d.createElementNS('http://www.w3.org/2000/svg','svg');svg.setAttribute('viewBox','0 0 24 24');svg.setAttribute('fill','none');svg.setAttribute('stroke','currentColor');svg.setAttribute('stroke-width','1.8');svg.setAttribute('stroke-linecap','round');svg.setAttribute('stroke-linejoin','round');svg.setAttribute('aria-hidden','true');const p=d.createElementNS(svg.namespaceURI,'path');p.setAttribute('d',paths[name]||paths.chat);svg.append(p);return svg;}
function hydrate(d){for(const node of d.querySelectorAll('[data-message-icon]')){node.replaceChildren(icon(d,node.dataset.messageIcon));}}
function relative(value,now=Date.now()){const date=new Date(value),minutes=Math.max(0,Math.floor((now-date.getTime())/60000));if(!Number.isFinite(minutes))return '';if(minutes<1)return 'Now';if(minutes<60)return minutes+'m';if(minutes<1440)return Math.floor(minutes/60)+'h';if(minutes<10080)return Math.floor(minutes/1440)+'d';return date.toLocaleDateString(undefined,{month:'short',day:'numeric'});}
function avatar(d,url,name){const node=d.createElement('span');node.className='avatar-shell';const initials=d.createElement('span');initials.className='avatar-initial';initials.textContent=(name||'M').trim().slice(0,1).toUpperCase()||'M';node.append(initials);try{const u=new URL(url);if(u.protocol==='https:'&&!u.username&&!u.password){const img=d.createElement('img');img.className='avatar';img.src=u.href;img.alt='';img.referrerPolicy='no-referrer';img.onerror=()=>img.remove();node.append(img);}}catch{}return node;}
function filter(rows,query,mode){const needle=query.trim().toLocaleLowerCase();return rows.filter(row=>(mode!=='unread'||Number(row.unread_count)>0)&&(!needle||[row.display_name,row.username,row.last_content].some(text=>String(text||'').toLocaleLowerCase().includes(needle))));}
function quick(d,rows){const fragment=d.createDocumentFragment(),seen=new Set();for(const row of rows){if(seen.has(row.contact_id))continue;seen.add(row.contact_id);if(seen.size>8)break;const link=d.createElement('a');link.className='quick-person';link.href='chat.html?host='+encodeURIComponent(row.contact_id);const name=row.display_name||row.username||'Member';link.append(avatar(d,row.avatar_url,name));const caption=d.createElement('span');caption.textContent=name;link.append(caption);fragment.append(link);}return fragment;}
function bubble(d,message){const node=d.createElement('div');node.className='message';const text=message.content||'';if(message.message_type==='image'){try{const url=new URL(message.image_url);if(url.protocol==='https:'&&!url.username&&!url.password){const a=d.createElement('a');if(global.MimoMedia)global.MimoMedia.display(a,url.href,'href');else a.href=url.href;a.target='_blank';a.rel='noopener noreferrer';a.className='chat-image-link';const img=d.createElement('img');if(global.MimoMedia)global.MimoMedia.display(img,url.href);else img.src=url.href;img.alt='Shared photo';img.loading='lazy';img.referrerPolicy='no-referrer';img.onerror=()=>{img.remove();a.textContent='Photo unavailable';};a.append(img);node.append(a);}}catch{}}
 const match=text.match(/^Mimo update\n(https:\/\/shelven123\.github\.io\/Mimo\/plaza\.html\?post=[0-9a-f-]{36})$/i);if(match){const card=d.createElement('a');card.className='shared-post';card.href=match[1];card.append(icon(d,'grid'));const label=d.createElement('span');label.textContent='Mimo update';const hint=d.createElement('small');hint.textContent='Tap to view this post';label.append(hint);card.append(label);node.append(card);}else if(text){const span=d.createElement('span');span.textContent=text;node.append(span);}if(!node.childNodes.length)node.textContent='Message unavailable';return node;}
function setupChat({d,getUser,canUse,getContact,onCall,onBlock,onPhoto}){hydrate(d);const dialog=d.getElementById('chatTools'),panel=d.getElementById('chatToolPanel'),input=d.getElementById('messageInput');let opener=null;function close(){dialog.close?.();dialog.removeAttribute('open');panel.replaceChildren();opener?.focus();}
 function open(title){if(!canUse())return false;opener=d.activeElement;d.getElementById('chatToolTitle').textContent=title;panel.replaceChildren();if(dialog.showModal)dialog.showModal();else dialog.setAttribute('open','');return true;}
 function button(label,fn){const b=d.createElement('button');b.className='tool-row';b.textContent=label;b.onclick=fn;panel.append(b);return b;}
 d.getElementById('emojiButton').onclick=()=>{if(!open('Quick reactions'))return;const grid=d.createElement('div');grid.className='chat-emoji';for(const value of ['❤️','🥰','😂','🥹','🔥','🙌','😍','😘','👍','✨','😊','😮']){const b=d.createElement('button');b.textContent=value;b.setAttribute('aria-label','Insert '+value);b.onclick=()=>{if(!canUse())return;const start=input.selectionStart||0,end=input.selectionEnd||0;if(input.value.length-(end-start)+value.length>1000)return;input.setRangeText(value,start,end,'end');close();input.focus();};grid.append(b);}panel.append(grid);};
 function theme(){panel.replaceChildren();d.getElementById('chatToolTitle').textContent='Chat theme';for(const [key,name] of [['midnight','Midnight'],['rose','Rose glow'],['ocean','Ocean glow']]){const b=button(name,()=>{d.body.dataset.chatTheme=key;try{localStorage.setItem('mimo-chat-theme',key);}catch{}close();});b.dataset.theme=key;}}
 d.getElementById('chatMore').onclick=()=>{if(!open('Conversation options'))return;button('View profile',()=>{location.href='profile.html?id='+encodeURIComponent(getContact().id);});button('Change chat theme',theme);button(d.getElementById('blockContact').textContent+' contact',async()=>{close();await onBlock();});};
 d.getElementById('chatPlus').onclick=()=>{if(!open('Chat tools'))return;if(onPhoto)button('Send a photo',()=>{close();onPhoto();});button('Change chat theme',theme);button('Clear unsent draft',()=>{input.value='';close();input.focus();});const note=d.createElement('p');note.className='tool-note';note.textContent='Voice messages and video attachments are not available yet.';panel.append(note);};
 d.getElementById('voiceCall').onclick=()=>onCall('voice');d.getElementById('videoCall').onclick=()=>onCall('video');d.getElementById('chatToolClose').onclick=close;dialog.addEventListener('cancel',()=>panel.replaceChildren());dialog.addEventListener('click',event=>{if(event.target===dialog)close();});
 try{const theme=localStorage.getItem('mimo-chat-theme');if(['midnight','rose','ocean'].includes(theme))d.body.dataset.chatTheme=theme;}catch{}
 function viewport(){const v=global.visualViewport;d.documentElement.style.setProperty('--chat-height',(v?.height||global.innerHeight)+'px');d.documentElement.style.setProperty('--chat-top',(v?.offsetTop||0)+'px');}global.visualViewport?.addEventListener('resize',viewport);global.visualViewport?.addEventListener('scroll',viewport);viewport();
 return {dispose(){close();global.visualViewport?.removeEventListener('resize',viewport);global.visualViewport?.removeEventListener('scroll',viewport);},close};
}
global.MimoMessagingUI={icon,hydrate,relative,avatar,filter,quick,bubble,setupChat};
})(window);
