(function(global){
'use strict';
const reasons={spam:'Spam / advertising',harassment:'Harassment / bullying',sexual:'Sexual content',violence:'Violence / dangerous content',fraud:'Fraud / scam',privacy:'Privacy violation',other:'Other'};
async function rpc(client,name,args){const {data,error}=await client.rpc(name,args);if(error)throw error;return data;}
async function mark(client,row,kind){const desired=kind==='bookmark'?!row.saved:!row.reposted;const result=await rpc(client,'mimo_plaza_mark',{target_post:row.id,kind,enabled:desired});if(result!==desired)throw Error('Action unavailable');}
function shareURL(id){if(!/^[0-9a-f-]{36}$/i.test(id))throw Error('Invalid post');return 'https://shelven123.github.io/Mimo/plaza.html?post='+id;}
function destinations(row){const url=shareURL(row.id),text='View '+(row.author_name||'a Host')+"'s update on Mimo";return {Facebook:'https://www.facebook.com/sharer/sharer.php?u='+encodeURIComponent(url),Telegram:'https://t.me/share/url?url='+encodeURIComponent(url)+'&text='+encodeURIComponent(text),X:'https://x.com/intent/tweet?url='+encodeURIComponent(url)+'&text='+encodeURIComponent(text),WhatsApp:'https://api.whatsapp.com/send?text='+encodeURIComponent(text+' '+url)};}
function validateFiles(files){if(files.length>3)throw Error('Attach up to 3 images.');for(const file of files)if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>10*1024*1024||file.size===0)throw Error('Use JPEG, PNG or WebP images up to 10 MB each.');}
async function compress(file){validateFiles([file]);const url=URL.createObjectURL(file);try{const img=new Image();img.src=url;await new Promise((resolve,reject)=>{img.onload=resolve;img.onerror=()=>reject(Error('Unable to read image'));});const width=img.naturalWidth,height=img.naturalHeight;if(!width||!height||width*height>40000000)throw Error('Image dimensions are too large');const scale=Math.min(1,1600/Math.max(width,height)),canvas=document.createElement('canvas');canvas.width=Math.round(width*scale);canvas.height=Math.round(height*scale);const ctx=canvas.getContext('2d');ctx.fillStyle='#fff';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.drawImage(img,0,0,canvas.width,canvas.height);const blob=await new Promise(resolve=>canvas.toBlob(resolve,'image/jpeg',.82));if(!blob||blob.size>3145728)throw Error('Compressed image must be under 3 MB');return blob;}finally{URL.revokeObjectURL(url);}}
async function upload(client,uid,attempt,files,alive=()=>true){validateFiles(files);attempt.paths=attempt.paths||[];attempt.uploaded=attempt.uploaded||new Set();for(let i=0;i<files.length;i++){if(!alive())throw Error('Session changed');const path=uid+'/'+attempt.id+'/'+(i+1)+'.jpg';if(!attempt.uploaded.has(path)){const blob=await compress(files[i]);if(!alive())throw Error('Session changed');const {error}=await client.storage.from('plaza-report-evidence').upload(path,blob,{contentType:'image/jpeg',upsert:false});if(error&&String(error.statusCode)!=='409'&&!/already exists|duplicate/i.test(error.message||''))throw error;if(!alive())throw Error('Session changed');attempt.uploaded.add(path);}attempt.paths[i]=path;}return attempt.paths;}
async function report(client,attempt,row,category,reason,paths){if(!Object.hasOwn(reasons,category))throw Error('Choose a report type');return rpc(client,'mimo_report_post',{request_id:attempt.id,target_post:row.id,report_category:category,report_reason:MimoPlaza.clean(reason,2000),paths});}
async function gifts(client){const rows=await rpc(client,'mimo_plaza_gifts');if(!Array.isArray(rows))throw Error('Gift catalog unavailable');return rows;}
global.MimoPlazaSocial={reasons,mark,shareURL,destinations,validateFiles,compress,upload,report,gifts};
})(window);
