(function(global){
 'use strict';
 const uuid=/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
 function clean(value,max){if(typeof value!=='string'||!value.trim()||value.trim().length>max)throw Error('Enter text within '+max+' characters.');return value.trim();}
 async function rpc(client,name,args){const {data,error}=await client.rpc(name,args);if(error)throw error;return data;}
 async function role(client){const value=await rpc(client,'mimo_plaza_role');if(!['user','host','admin'].includes(value))throw Error('Profile unavailable');return value;}
 async function feed(client,offset=0){const rows=await rpc(client,'mimo_plaza_feed',{page_size:20,page_offset:offset});if(!Array.isArray(rows))throw Error('Feed unavailable');return rows;}
 async function comments(client,post,offset=0){const rows=await rpc(client,'mimo_plaza_comments',{target_post:post,page_size:30,page_offset:offset});if(!Array.isArray(rows))throw Error('Comments unavailable');return rows;}
 async function publish(client,id,body){return rpc(client,'mimo_publish_post',{request_id:id,body:clean(body,2000)});}
 async function comment(client,id,post,body){return rpc(client,'mimo_comment_post',{request_id:id,target_post:post,body:clean(body,1000)});}
 async function like(client,post,desired){if(typeof desired!=='boolean')throw Error('Invalid like state');const result=await rpc(client,'mimo_plaza_like',{target_post:post,liked:desired});if(result!==desired)throw Error('Like unavailable');}
 async function remove(client,table,id,uid){if(!['posts','post_comments'].includes(table))throw Error('Invalid content type');const {data,error}=await client.from(table).delete().eq('id',id).eq(table==='posts'?'author_id':'user_id',uid).select('id');if(error)throw error;if(!Array.isArray(data)||data.length!==1)throw Error('Content changed or unavailable. Refresh to retry.');}
 function profile(document,id,name){if(!uuid.test(id||'')){const text=document.createElement('strong');text.textContent=name;return text;}const link=document.createElement('a');link.href='profile.html?id='+id;link.textContent=name;return link;}
 function imageURL(value){try{const url=new URL(value);return url.protocol==='https:'&&!url.username&&!url.password?url.href:null;}catch{return null;}}
 function renderFeed(document,rows,uid,handlers){const fragment=document.createDocumentFragment();for(const row of rows){const article=document.createElement('article');article.className='post';const heading=document.createElement('div');heading.className='post-head';heading.append(profile(document,row.author_id,row.author_name));const time=document.createElement('time');time.textContent=new Date(row.created_at).toLocaleString();heading.append(time);const body=document.createElement('p');body.textContent=row.content||'';article.append(heading,body);
 for(const value of (Array.isArray(row.image_urls)?row.image_urls:[]).slice(0,6)){const url=imageURL(value);if(url){const image=document.createElement('img');image.src=url;image.alt='Post image';image.loading='lazy';image.referrerPolicy='no-referrer';article.append(image);}}
 const actions=document.createElement('div');actions.className='actions';const like=document.createElement('button');like.textContent=(row.liked?'♥ Liked':'♡ Like')+' · '+row.likes;like.setAttribute('aria-pressed',String(row.liked));like.onclick=()=>handlers.like(row);const comment=document.createElement('button');comment.textContent='Comments · '+row.comments;comment.onclick=()=>handlers.comments(row);actions.append(like,comment);if(row.author_id===uid){const remove=document.createElement('button');remove.textContent='Delete post';remove.onclick=()=>handlers.remove(row);actions.append(remove);}article.append(actions);fragment.append(article);}return fragment;}
 function renderComments(document,rows,uid,remove){const fragment=document.createDocumentFragment();for(const row of rows){const article=document.createElement('article');article.className='comment';article.append(profile(document,row.user_id,row.author_name));const body=document.createElement('p');body.textContent=row.content;const time=document.createElement('time');time.textContent=new Date(row.created_at).toLocaleString();article.append(body,time);if(row.user_id===uid){const button=document.createElement('button');button.textContent='Delete comment';button.onclick=()=>remove(row);article.append(button);}fragment.append(article);}return fragment;}
 global.MimoPlaza={clean,role,feed,comments,publish,comment,like,remove,imageURL,renderFeed,renderComments};
})(window);
