(function(global){
 'use strict';
 const uuid=/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
 function clean(value,max){if(typeof value!=='string'||!value.trim()||value.trim().length>max)throw Error('Enter text within '+max+' characters.');return value.trim();}
 async function rpc(client,name,args){const {data,error}=await client.rpc(name,args);if(error)throw error;return data;}
 async function role(client){const value=await rpc(client,'mimo_plaza_role');if(!['user','host','admin'].includes(value))throw Error('Profile unavailable');return value;}
 async function feed(client,offset=0,mode='all',target=null,media='all'){const rows=await rpc(client,'mimo_plaza_feed_v3',{page_size:20,page_offset:offset,feed_mode:mode,target_post:target,media_filter:media});if(!Array.isArray(rows))throw Error('Feed unavailable');return rows;}
 async function comments(client,post,offset=0,parent=null){const rows=await rpc(client,'mimo_plaza_comments_v2',{target_post:post,page_size:30,page_offset:offset,reply_to:parent});if(!Array.isArray(rows))throw Error('Comments unavailable');return rows;}
 async function publish(client,id,body){return rpc(client,'mimo_publish_post',{request_id:id,body:clean(body,2000)});}
 async function comment(client,id,post,body,parent=null){return rpc(client,'mimo_comment_reply',{request_id:id,target_post:post,body:clean(body,1000),reply_to:parent});}
 async function like(client,post,desired){if(typeof desired!=='boolean')throw Error('Invalid like state');const result=await rpc(client,'mimo_plaza_like',{target_post:post,liked:desired});if(result!==desired)throw Error('Like unavailable');}
 async function remove(client,table,id,uid){if(!['posts','post_comments'].includes(table))throw Error('Invalid content type');const {data,error}=await client.from(table).delete().eq('id',id).eq(table==='posts'?'author_id':'user_id',uid).select('id');if(error)throw error;if(!Array.isArray(data)||data.length!==1)throw Error('Content changed or unavailable. Refresh to retry.');}
 function profile(document,id,name){if(!uuid.test(id||'')){const text=document.createElement('strong');text.textContent=name;return text;}const link=document.createElement('a');link.href='profile.html?id='+id;link.textContent=name;return link;}
 function imageURL(value){try{const url=new URL(value);return url.protocol==='https:'&&!url.username&&!url.password?url.href:null;}catch{return null;}}
 const paths={heart:'M20.8 4.6a5.5 5.5 0 0 0-7.8 0L12 5.7l-1.1-1.1a5.5 5.5 0 0 0-7.8 7.8L12 21l8.8-8.6a5.5 5.5 0 0 0 0-7.8Z',comment:'M21 11.5a8.4 8.4 0 0 1-8.5 8.5 9.5 9.5 0 0 1-4-.9L3 21l1.9-5.5a9.5 9.5 0 0 1-.9-4A8.4 8.4 0 0 1 12.5 3H13a8.4 8.4 0 0 1 8 8v.5Z',repost:'M4 8h14l-4-4M20 16H6l4 4M18 8l-4 4M6 16l4-4',share:'m22 2-7 20-4-9-9-4 20-7ZM22 2 11 13',save:'M5 3h14v18l-7-5-7 5V3Z',gift:'M3 8h18v4H3V8ZM5 12v9h14v-9M12 8v13M12 8H8a3 3 0 1 1 3-3l1 3ZM12 8h4a3 3 0 1 0-3-3l-1 3Z',grid:'M3 3h5v5H3V3ZM10 3h4v5h-4V3ZM16 3h5v5h-5V3ZM3 10h5v4H3v-4ZM10 10h4v4h-4v-4ZM16 10h5v4h-5v-4ZM3 16h5v5H3v-5ZM10 16h4v5h-4v-5ZM16 16h5v5h-5v-5',reel:'M5 3h14a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2ZM10 8l6 4-6 4V8Z',more:'M5 12h.01M12 12h.01M19 12h.01'};
 function icon(document,name){const svg=document.createElementNS('http://www.w3.org/2000/svg','svg');svg.setAttribute('viewBox','0 0 24 24');svg.setAttribute('aria-hidden','true');svg.setAttribute('fill','none');svg.setAttribute('stroke','currentColor');svg.setAttribute('stroke-width','1.8');svg.setAttribute('stroke-linecap','round');svg.setAttribute('stroke-linejoin','round');const path=document.createElementNS(svg.namespaceURI,'path');path.setAttribute('d',paths[name]);svg.append(path);return svg;}
 function action(document,name,label,fn,pressed,count){const button=document.createElement('button');button.className='icon-action '+(pressed?'is-on':'');button.setAttribute('aria-label',label);button.title=label;button.append(icon(document,name));if(typeof pressed==='boolean')button.setAttribute('aria-pressed',String(pressed));if(count!==undefined){const span=document.createElement('span');span.textContent=count;button.append(span);}button.onclick=fn;return button;}
 function lastSeen(row){if(row.online_status==='online')return 'Online';if(!row.last_seen_at)return 'Last seen unavailable';const date=new Date(row.last_seen_at);return Number.isFinite(date.getTime())?'Last seen '+date.toLocaleString():'Last seen unavailable';}
 function renderFeed(document,rows,uid,handlers){const fragment=document.createDocumentFragment();for(const row of rows){const article=document.createElement('article');article.className='post';article.dataset.author=row.author_id;article.id='post-'+row.id;const heading=document.createElement('div');heading.className='post-head';const avatar=document.createElement('span');avatar.className='avatar';const avatarURL=imageURL(row.avatar_url);if(avatarURL){const img=document.createElement('img');img.src=avatarURL;img.alt='';img.referrerPolicy='no-referrer';img.onerror=()=>{img.remove();avatar.textContent=(row.author_name||'H').slice(0,1);};avatar.append(img);}else avatar.textContent=(row.author_name||'H').slice(0,1);
 const details=document.createElement('div');details.className='author-info';const name=profile(document,row.author_id,row.author_name);name.className='author-name';const badge=document.createElement('span');badge.className='host-badge';badge.textContent='HOST';const about=document.createElement('div');about.className='author-about';about.textContent=[Number.isInteger(row.age)?row.age+' years':null,row.region||'Region unavailable'].filter(Boolean).join(' · ');const seen=document.createElement('div');seen.className='last-seen';seen.textContent=lastSeen(row);details.append(name,badge,about,seen);heading.append(avatar,details,action(document,'more','Post options',()=>handlers.menu?.(row)));const body=document.createElement('p');body.className='post-body';body.textContent=row.content||'';article.append(heading,body);
 const media=document.createElement('div');media.className='post-media';const videoURL=imageURL(row.video_url);if(videoURL){article.classList.add('reel-post');const video=document.createElement('video');video.src=videoURL;video.controls=true;video.playsInline=true;video.preload='none';const poster=imageURL(row.image_urls?.[0]);if(poster)video.poster=poster;video.setAttribute('aria-label','Reel by '+row.author_name);video.onerror=()=>{video.setAttribute('aria-label','Video unavailable');};media.append(video);}for(const value of (videoURL?[]:Array.isArray(row.image_urls)?row.image_urls:[]).slice(0,6)){const url=imageURL(value);if(url){const image=document.createElement('img');image.src=url;image.alt='Post image';image.loading='lazy';image.referrerPolicy='no-referrer';media.append(image);}}
 const gift=action(document,'gift','Send a gift',()=>handlers.gift?.(row));gift.classList.add('gift-trigger');if(media.children.length){media.append(gift);article.append(media);}const actions=document.createElement('div');actions.className='actions';actions.append(action(document,'heart',row.liked?'Unlike':'Like',()=>handlers.like(row),row.liked,row.likes),action(document,'comment','Comments',()=>handlers.comments(row),undefined,row.comments),action(document,'repost',row.reposted?'Undo repost':'Repost',()=>handlers.repost?.(row),!!row.reposted,row.reposts||'0'),action(document,'share','Share',()=>handlers.share?.(row)),action(document,'save',row.saved?'Remove saved post':'Save post',()=>handlers.save?.(row),!!row.saved));if(!media.children.length)actions.append(gift);article.append(actions);const time=document.createElement('time');time.className='post-date';time.textContent=new Date(row.created_at).toLocaleString();article.append(time);fragment.append(article);}return fragment;}
 function avatar(document,url,name){const node=document.createElement('span');node.className='avatar';const safe=imageURL(url);if(safe){const img=document.createElement('img');img.src=safe;img.alt='';img.referrerPolicy='no-referrer';img.onerror=()=>{img.remove();node.textContent=(name||'M').slice(0,1);};node.append(img);}else node.textContent=(name||'M').slice(0,1);return node;}
 function renderComments(document,rows,uid,remove,handlers={}){const fragment=document.createDocumentFragment();for(const row of rows){const article=document.createElement('article');article.className='comment';article.dataset.comment=row.id;article.append(avatar(document,row.avatar_url,row.author_name));const details=document.createElement('div');details.className='comment-copy';const heading=document.createElement('div');heading.className='comment-heading';heading.append(profile(document,row.user_id,row.author_name));const time=document.createElement('time');time.textContent=new Date(row.created_at).toLocaleDateString(undefined,{month:'short',day:'numeric'});heading.append(time);const body=document.createElement('p');body.textContent=row.content;const meta=document.createElement('div');meta.className='comment-meta';if(row.author_liked){const liked=document.createElement('span');liked.textContent='♥ Liked by author';meta.append(liked);}const reply=document.createElement('button');reply.textContent='Reply';reply.onclick=()=>handlers.reply?.(row);meta.append(reply);if(row.user_id===uid){const button=document.createElement('button');button.textContent='Delete';button.onclick=()=>remove(row);meta.append(button);}details.append(heading,body,meta);if(!row.parent_id&&Number(row.replies)>0){const more=document.createElement('button');more.className='thread-toggle';more.textContent='View replies ('+row.replies+')';more.onclick=()=>handlers.expand?.(row,article,more);details.append(more);}article.append(details,action(document,'heart',row.liked?'Unlike comment':'Like comment',()=>handlers.like?.(row),!!row.liked,row.likes||'0'));fragment.append(article);}return fragment;}
 function renderGrid(document,rows,open){const fragment=document.createDocumentFragment();for(const row of rows){const url=imageURL(row.image_urls?.[0]);const tile=document.createElement('button');tile.className='media-tile';tile.setAttribute('aria-label',(row.video_url?'Open Reel':'Open photos')+' by '+row.author_name);if(url){const img=document.createElement('img');img.src=url;img.alt=row.content||'Post';img.loading='lazy';img.referrerPolicy='no-referrer';tile.append(img);}else {const bg=document.createElement('span');bg.className='tile-placeholder';bg.append(icon(document,'reel'));tile.append(bg);}if(row.video_url||row.image_urls?.length>1){const badge=document.createElement('span');badge.className='tile-badge';badge.append(icon(document,row.video_url?'reel':'grid'));tile.append(badge);}const name=document.createElement('span');name.className='tile-name';name.textContent=row.author_name;tile.append(name);tile.onclick=()=>open(row);fragment.append(tile);}return fragment;}
 global.MimoPlaza={avatar,renderGrid,icon,action,lastSeen,clean,role,feed,comments,publish,comment,like,remove,imageURL,renderFeed,renderComments};
})(window);
