(function(global){
 'use strict';
 const uuid=/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
 function clean(value,max){if(typeof value!=='string'||!value.trim()||value.trim().length>max)throw Error('Enter text within '+max+' characters.');return value.trim();}
 async function rpc(client,name,args){const {data,error}=await client.rpc(name,args);if(error)throw error;return data;}
 async function role(client){const value=await rpc(client,'mimo_plaza_role');if(!['user','host','admin'].includes(value))throw Error('Profile unavailable');return value;}
 async function feed(client,offset=0,mode='all',target=null){const rows=await rpc(client,'mimo_plaza_feed_v2',{page_size:20,page_offset:offset,feed_mode:mode,target_post:target});if(!Array.isArray(rows))throw Error('Feed unavailable');return rows;}
 async function comments(client,post,offset=0){const rows=await rpc(client,'mimo_plaza_comments',{target_post:post,page_size:30,page_offset:offset});if(!Array.isArray(rows))throw Error('Comments unavailable');return rows;}
 async function publish(client,id,body){return rpc(client,'mimo_publish_post',{request_id:id,body:clean(body,2000)});}
 async function comment(client,id,post,body){return rpc(client,'mimo_comment_post',{request_id:id,target_post:post,body:clean(body,1000)});}
 async function like(client,post,desired){if(typeof desired!=='boolean')throw Error('Invalid like state');const result=await rpc(client,'mimo_plaza_like',{target_post:post,liked:desired});if(result!==desired)throw Error('Like unavailable');}
 async function remove(client,table,id,uid){if(!['posts','post_comments'].includes(table))throw Error('Invalid content type');const {data,error}=await client.from(table).delete().eq('id',id).eq(table==='posts'?'author_id':'user_id',uid).select('id');if(error)throw error;if(!Array.isArray(data)||data.length!==1)throw Error('Content changed or unavailable. Refresh to retry.');}
 function profile(document,id,name){if(!uuid.test(id||'')){const text=document.createElement('strong');text.textContent=name;return text;}const link=document.createElement('a');link.href='profile.html?id='+id;link.textContent=name;return link;}
 function imageURL(value){try{const url=new URL(value);return url.protocol==='https:'&&!url.username&&!url.password?url.href:null;}catch{return null;}}
 const paths={heart:'M20.8 4.6a5.5 5.5 0 0 0-7.8 0L12 5.7l-1.1-1.1a5.5 5.5 0 0 0-7.8 7.8L12 21l8.8-8.6a5.5 5.5 0 0 0 0-7.8Z',comment:'M21 11.5a8.4 8.4 0 0 1-8.5 8.5 9.5 9.5 0 0 1-4-.9L3 21l1.9-5.5a9.5 9.5 0 0 1-.9-4A8.4 8.4 0 0 1 12.5 3H13a8.4 8.4 0 0 1 8 8v.5Z',repost:'M4 8h14l-4-4M20 16H6l4 4M18 8l-4 4M6 16l4-4',share:'m22 2-7 20-4-9-9-4 20-7ZM22 2 11 13',save:'M5 3h14v18l-7-5-7 5V3Z',gift:'M3 8h18v4H3V8ZM5 12v9h14v-9M12 8v13M12 8H8a3 3 0 1 1 3-3l1 3ZM12 8h4a3 3 0 1 0-3-3l-1 3Z',more:'M5 12h.01M12 12h.01M19 12h.01'};
 function icon(document,name){const svg=document.createElementNS('http://www.w3.org/2000/svg','svg');svg.setAttribute('viewBox','0 0 24 24');svg.setAttribute('aria-hidden','true');svg.setAttribute('fill','none');svg.setAttribute('stroke','currentColor');svg.setAttribute('stroke-width','1.8');svg.setAttribute('stroke-linecap','round');svg.setAttribute('stroke-linejoin','round');const path=document.createElementNS(svg.namespaceURI,'path');path.setAttribute('d',paths[name]);svg.append(path);return svg;}
 function action(document,name,label,fn,pressed,count){const button=document.createElement('button');button.className='icon-action '+(pressed?'is-on':'');button.setAttribute('aria-label',label);button.title=label;button.append(icon(document,name));if(typeof pressed==='boolean')button.setAttribute('aria-pressed',String(pressed));if(count!==undefined){const span=document.createElement('span');span.textContent=count;button.append(span);}button.onclick=fn;return button;}
 function lastSeen(row){if(row.online_status==='online')return 'Online';if(!row.last_seen_at)return 'Last seen unavailable';const date=new Date(row.last_seen_at);return Number.isFinite(date.getTime())?'Last seen '+date.toLocaleString():'Last seen unavailable';}
 function renderFeed(document,rows,uid,handlers){const fragment=document.createDocumentFragment();for(const row of rows){const article=document.createElement('article');article.className='post';article.dataset.author=row.author_id;article.id='post-'+row.id;const heading=document.createElement('div');heading.className='post-head';const avatar=document.createElement('span');avatar.className='avatar';const avatarURL=imageURL(row.avatar_url);if(avatarURL){const img=document.createElement('img');img.src=avatarURL;img.alt='';img.referrerPolicy='no-referrer';img.onerror=()=>{img.remove();avatar.textContent=(row.author_name||'H').slice(0,1);};avatar.append(img);}else avatar.textContent=(row.author_name||'H').slice(0,1);
 const details=document.createElement('div');details.className='author-info';const name=profile(document,row.author_id,row.author_name);name.className='author-name';const badge=document.createElement('span');badge.className='host-badge';badge.textContent='HOST';const about=document.createElement('div');about.className='author-about';about.textContent=[Number.isInteger(row.age)?row.age+' years':null,row.region||'Region unavailable'].filter(Boolean).join(' · ');const seen=document.createElement('div');seen.className='last-seen';seen.textContent=lastSeen(row);details.append(name,badge,about,seen);heading.append(avatar,details,action(document,'more','Post options',()=>handlers.menu?.(row)));const body=document.createElement('p');body.className='post-body';body.textContent=row.content||'';article.append(heading,body);
 const media=document.createElement('div');media.className='post-media';for(const value of (Array.isArray(row.image_urls)?row.image_urls:[]).slice(0,6)){const url=imageURL(value);if(url){const image=document.createElement('img');image.src=url;image.alt='Post image';image.loading='lazy';image.referrerPolicy='no-referrer';media.append(image);}}
 const gift=action(document,'gift','Send a gift',()=>handlers.gift?.(row));gift.classList.add('gift-trigger');if(media.children.length){media.append(gift);article.append(media);}const actions=document.createElement('div');actions.className='actions';actions.append(action(document,'heart',row.liked?'Unlike':'Like',()=>handlers.like(row),row.liked,row.likes),action(document,'comment','Comments',()=>handlers.comments(row),undefined,row.comments),action(document,'repost',row.reposted?'Undo repost':'Repost',()=>handlers.repost?.(row),!!row.reposted,row.reposts||'0'),action(document,'share','Share',()=>handlers.share?.(row)),action(document,'save',row.saved?'Remove saved post':'Save post',()=>handlers.save?.(row),!!row.saved));if(!media.children.length)actions.append(gift);article.append(actions);const time=document.createElement('time');time.className='post-date';time.textContent=new Date(row.created_at).toLocaleString();article.append(time);fragment.append(article);}return fragment;}
 function renderComments(document,rows,uid,remove){const fragment=document.createDocumentFragment();for(const row of rows){const article=document.createElement('article');article.className='comment';article.append(profile(document,row.user_id,row.author_name));const body=document.createElement('p');body.textContent=row.content;const time=document.createElement('time');time.textContent=new Date(row.created_at).toLocaleString();article.append(body,time);if(row.user_id===uid){const button=document.createElement('button');button.textContent='Delete comment';button.onclick=()=>remove(row);article.append(button);}fragment.append(article);}return fragment;}
 global.MimoPlaza={icon,action,lastSeen,clean,role,feed,comments,publish,comment,like,remove,imageURL,renderFeed,renderComments};
})(window);
