(function(global){
'use strict';
function create({dialog,stream,status,more,closeButton,tabs,getUser,fetchPage,getHandlers,onState=()=>{}}){
 const doc=dialog.ownerDocument;let rows=[],offset=0,mode='all',generation=0,loading=false,ended=false,disposed=false,playback=null,savedOverflow='',origin=null,soundMuted=false;
 const alive=()=>!disposed&&dialog.hasAttribute('open')&&!!getUser();
 function draw(){global.MimoPlaza.reconcileFeed(stream,rows,getUser(),getHandlers());playback?.sync();more.hidden=ended;}
 function reset(){playback?.dispose();playback=null;global.MimoPlaza.stopMedia(stream);stream.replaceChildren();rows=[];offset=0;ended=false;origin=null;stream.scrollTop=0;}
 function makePlayback(){playback=global.MimoReelPlayback?.create(stream,alive,()=>false,{observerRoot:stream,rootMargin:'0px',enablePause:true,defaultMuted:()=>soundMuted,onSoundChange:value=>{soundMuted=value;},initialState:video=>{if(origin&&video.closest('article').id==='post-'+origin.id){const state=origin;origin=null;return state;}return null;}});}
 async function load(){if(!alive()||loading||ended)return;loading=true;more.disabled=true;status.textContent='Loading Reels…';const token=generation,owner=getUser();try{const page=await fetchPage(offset,mode);if(token!==generation||!alive()||owner!==getUser())return;offset+=page.length;ended=page.length<20;const map=new Map(rows.map(row=>[row.id,row]));for(const row of page)if(row.video_url)map.set(row.id,row);rows=Array.from(map.values());draw();status.textContent=rows.length?'':mode==='following'?'Follow hosts to see their Reels here.':'No Reels yet.';}catch{if(token===generation&&alive())status.textContent='Unable to load Reels. Tap Retry.';}finally{if(token===generation){loading=false;more.disabled=false;more.hidden=ended;more.textContent='Load more / Retry';}}}
 function switchMode(value){if(!alive()||mode===value)return;generation++;loading=false;mode=value;reset();for(const tab of tabs){tab.classList.toggle('active',tab.dataset.reelsMode===mode);tab.setAttribute('aria-pressed',String(tab.dataset.reelsMode===mode));}makePlayback();load();}
 function close(){generation++;loading=false;reset();dialog.close?.();dialog.removeAttribute('open');doc.documentElement.style.overflow=savedOverflow;status.textContent='';onState(false);}
 function open(row,video,currentMode='all'){if(disposed||!getUser())return;generation++;loading=false;if(alive())reset();else savedOverflow=doc.documentElement.style.overflow;mode=currentMode==='following'?'following':'all';soundMuted=false;const source=video?.currentSrc||video?.src,poster=video?.poster;origin={id:row.id,time:video?.currentTime||0,muted:false};rows=[row];if(!dialog.hasAttribute('open')){if(dialog.showModal)dialog.showModal();else dialog.setAttribute('open','');}doc.documentElement.style.overflow='hidden';onState(true);for(const tab of tabs){tab.classList.toggle('active',tab.dataset.reelsMode===mode);tab.setAttribute('aria-pressed',String(tab.dataset.reelsMode===mode));}draw();const player=stream.querySelector('video');if(player&&source&&global.MimoPlaza.imageURL(source)){if(!global.mimoMediaResolver?.adopt?.(player,row.video_url,source)){global.mimoMediaResolver?.forget?.(player);player.src=source;}if(poster)player.poster=poster;}makePlayback();playback?.start(player);load();}
 function refresh(updated){if(!alive())return;const map=new Map(updated.map(row=>[row.id,row])),visibleIds=new Set(Array.from(stream.children).map(node=>node.id));rows=rows.filter(row=>visibleIds.has('post-'+row.id)).map(row=>map.get(row.id)||row);draw();}
 async function refreshCurrent(){if(!alive())return;const token=generation,owner=getUser(),current=stream.children[Math.round(stream.scrollTop/(stream.clientHeight||1))];const id=current?.id.replace('post-','');if(!id)return;try{const result=await global.MimoPlaza.feed(global.mimoPlazaClient,0,mode,id,'reels');if(token!==generation||!alive()||owner!==getUser())return;if(result.length)refresh(result);else{rows=rows.filter(row=>row.id!==id);draw();}}catch{if(alive()&&token===generation)status.textContent='Unable to refresh. Retry when connected.';}}
 function scroll(){if(stream.scrollHeight-stream.scrollTop-stream.clientHeight<stream.clientHeight*2)load();}
 function keyboard(event){if(event.key==='ArrowDown'||event.key==='ArrowUp'){event.preventDefault();stream.scrollBy?.({top:stream.clientHeight*(event.key==='ArrowDown'?1:-1),behavior:'smooth'});}}
 more.onclick=load;closeButton.onclick=close;for(const tab of tabs)tab.onclick=()=>switchMode(tab.dataset.reelsMode);dialog.addEventListener('cancel',event=>{event.preventDefault();close();});stream.addEventListener('scroll',scroll,{passive:true});stream.addEventListener('keydown',keyboard);
 return {open,close,refresh,refreshCurrent,isOpen:alive,dispose(){close();disposed=true;stream.removeEventListener('scroll',scroll);stream.removeEventListener('keydown',keyboard);}};
}
global.MimoReelsViewer={create};
})(window);
