(function(global){
 'use strict';
 const categories=['general','account','payment','diamond','vip','withdrawal','host','report','technical','other'];
 function clean(value,max){if(typeof value!=='string'||!value.trim()||value.trim().length>max)throw Error('Enter text within '+max+' characters.');return value.trim();}
 async function rpc(client,name,args){const {data,error}=await client.rpc(name,args);if(error)throw error;return data;}
 async function access(client){const value=await rpc(client,'mimo_support_access');if(typeof value!=='boolean')throw Error('Access unavailable');return value;}
 async function tickets(client,uid,all,offset=0){let query=client.from('support_tickets').select('id,user_id,subject,category,priority,status,created_at,updated_at');if(!all)query=query.eq('user_id',uid);const {data,error}=await query.order('created_at',{ascending:false}).order('id',{ascending:false}).range(offset,offset+29);if(error||!Array.isArray(data))throw error||Error('Tickets unavailable');return data;}
 async function detail(client,id){const {data,error}=await client.from('support_tickets').select('id,user_id,subject,category,priority,status,created_at,updated_at').eq('id',id).single();if(error||!data)throw error||Error('Ticket unavailable');return data;}
 async function messages(client,id,offset=0){const {data,error}=await client.from('support_messages').select('id,ticket_id,sender_id,message,created_at').eq('ticket_id',id).order('created_at',{ascending:true}).order('id',{ascending:true}).range(offset,offset+49);if(error||!Array.isArray(data))throw error||Error('Replies unavailable');return data;}
 async function open(client,id,subject,category,body){if(!categories.includes(category))throw Error('Choose a category');return rpc(client,'mimo_open_support',{request_id:id,ticket_subject:clean(subject,120),ticket_category:category,body:clean(body,4000)});}
 async function reply(client,id,ticket,body){return rpc(client,'mimo_reply_support',{request_id:id,target_ticket:ticket,body:clean(body,4000)});}
 async function transition(client,row,status,priority=null){if(!await rpc(client,'mimo_support_transition',{target_ticket:row.id,expected_status:row.status,next_status:status,next_priority:priority}))throw Error('Ticket changed. Refresh before trying again.');}
 function renderTickets(document,rows,choose){const fragment=document.createDocumentFragment();for(const row of rows){const button=document.createElement('button');button.className='ticket';const title=document.createElement('strong');title.textContent=row.subject;const info=document.createElement('span');info.textContent=row.category+' · '+row.status+' · '+row.priority;button.append(title,info);button.onclick=()=>choose(row.id);fragment.append(button);}return fragment;}
 function renderMessages(document,rows,owner,uid){const fragment=document.createDocumentFragment();for(const row of rows){const article=document.createElement('article');article.className='message';const label=document.createElement('strong');label.textContent=row.sender_id===uid?'You':row.sender_id===owner?'Requester':'Support';const body=document.createElement('p');body.textContent=row.message;const time=document.createElement('time');time.textContent=new Date(row.created_at).toLocaleString();article.append(label,body,time);fragment.append(article);}return fragment;}
 global.MimoSupport={categories,clean,access,tickets,detail,messages,open,reply,transition,renderTickets,renderMessages};
})(window);
