(function(global){
'use strict';
const BUCKET='mimo-media',PAGE=30;
function bytes(value){if(value===null||value===undefined||!/^\d+$/.test(String(value)))return 'Size unavailable';const n=Number(value);if(!Number.isFinite(n))return 'Size unavailable';return n<1048576?(n/1024).toFixed(1)+' KB':(n/1048576).toFixed(1)+' MB';}
async function list(client,cursor=null){const {data,error}=await client.rpc('mimo_my_uploads',{after_path:cursor});if(error)throw error;if(!Array.isArray(data))throw Error('Invalid upload response');return {rows:data.slice(0,PAGE),more:data.length>PAGE};}
async function remove(client,row,uid){if(!uid||!row.can_remove||row.in_use||typeof row.path!=='string'||row.path.split('/')[0]!==uid)throw Error('This file cannot be removed.');const claim=await client.rpc('mimo_claim_unused_upload',{media_path:row.path});if(claim.error)throw claim.error;if(claim.data!==true)throw Error('File could not be marked for removal.');const {data,error}=await client.storage.from(BUCKET).remove([row.path]);if(error)throw error;if(!Array.isArray(data)||!data.some(item=>item.name===row.path))throw Error('Deletion was not confirmed. Refresh to check whether the file is still present.');}
function render(doc,rows,onRemove){const fragment=doc.createDocumentFragment();for(const row of rows){const article=doc.createElement('article');article.className='upload';const icon=doc.createElement('span');icon.className='file-icon';icon.textContent=String(row.mime||'').startsWith('video/')?'▷':'▧';icon.setAttribute('aria-hidden','true');const info=doc.createElement('div');info.className='file-info';const name=doc.createElement('strong');name.textContent=row.path.split('/').pop()||'Uploaded file';const meta=doc.createElement('span');const date=new Date(row.uploaded_at);meta.textContent=(row.path.split('/')[1]==='chats'?'Chat photo':'Plaza media')+' · '+bytes(row.bytes)+' · '+(Number.isNaN(date.getTime())?'Date unavailable':date.toLocaleString());const status=doc.createElement('span');status.className=row.in_use?'used':'unused';status.textContent=row.in_use?'In use':row.can_remove?'Unused · ready to remove':'Unused · protected for 24 hours';info.append(name,meta,status);article.append(icon,info);if(row.can_remove&&!row.in_use){const button=doc.createElement('button');button.className='remove';button.textContent='Remove';button.onclick=()=>onRemove(row);article.append(button);}fragment.append(article);}return fragment;}
global.MimoUploads=Object.freeze({list,remove,render,bytes});
})(window);
