const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');const {PGlite}=require('@electric-sql/pglite'),{JSDOM}=require('jsdom'),root=path.join(__dirname,'..');
const A='10000000-0000-4000-8000-000000000001',B='20000000-0000-4000-8000-000000000002',C='30000000-0000-4000-8000-000000000003',T='40000000-0000-4000-8000-000000000004',R='50000000-0000-4000-8000-000000000005';
test('Plaza enforces Host publishing, block visibility, ownership and retry-safe writes',async t=>{
 const db=new PGlite();await db.exec(fs.readFileSync(__dirname+'/contact-policy-fixture.sql','utf8'));await db.exec(fs.readFileSync(root+'/supabase/migrations/20261009233713_mimo_contact_permissions.sql','utf8'));await db.exec(`alter table profiles add display_name text;alter table profiles add username text;
 create table posts(id uuid default gen_random_uuid() primary key,author_id uuid not null references profiles(id),content text,image_urls text[] default '{}',created_at timestamptz not null default now(),updated_at timestamptz not null default now());
 create table post_likes(post_id uuid references posts(id) on delete cascade,user_id uuid references profiles(id),created_at timestamptz not null default now(),primary key(post_id,user_id));
 create table post_comments(id uuid default gen_random_uuid() primary key,post_id uuid not null references posts(id) on delete cascade,user_id uuid not null references profiles(id),content text not null,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
 alter table posts enable row level security;alter table post_likes enable row level security;alter table post_comments enable row level security;grant all on posts,post_likes,post_comments to authenticated,anon;
 create policy posts_select_authenticated on posts for select to authenticated using(true);
 create policy posts_insert_host on posts for insert to authenticated with check(author_id=auth.uid() and exists(select 1 from profiles where id=auth.uid() and role='host'));
 create policy posts_update_own on posts for update to authenticated using(author_id=auth.uid()) with check(author_id=auth.uid());create policy posts_delete_own on posts for delete to authenticated using(author_id=auth.uid());
 create policy post_likes_select_authenticated on post_likes for select to authenticated using(true);create policy post_likes_insert_own on post_likes for insert to authenticated with check(user_id=auth.uid());create policy post_likes_delete_own on post_likes for delete to authenticated using(user_id=auth.uid());
 create policy comments_select_authenticated on post_comments for select to authenticated using(true);create policy comments_insert_own on post_comments for insert to authenticated with check(user_id=auth.uid());create policy comments_update_own on post_comments for update to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid());create policy comments_delete_own on post_comments for delete to authenticated using(user_id=auth.uid());
 insert into profiles(id,role,display_name) values('${A}','user','User'),('${B}','host','Host'),('${C}','host','Another Host');`);
 await db.exec(fs.readFileSync(root+'/supabase/migrations/20261010143000_mimo_plaza.sql','utf8'));
 const actor=async(id,role='authenticated')=>{await db.exec('reset role');await db.query("select set_config('request.jwt.claim.sub',$1,false)",[id||'']);await db.exec('set role '+role);};const denied=p=>assert.rejects(p,e=>e.code==='42501');
 await t.test('Only Host can publish trimmed bounded text, retry without duplicates; no arbitrary images',async()=>{
  await actor(A);await denied(db.query('select mimo_publish_post($1,$2)',[T,'hello']));await actor(B);await db.query('select mimo_publish_post($1,$2)',[T,' Hello Plaza ']);await db.query('select mimo_publish_post($1,$2)',[T,'Hello Plaza']);assert.equal((await db.query('select count(*) n from posts')).rows[0].n,1);await denied(db.query('select mimo_publish_post($1,$2)',[T,'changed']));await denied(db.query('select mimo_publish_post($1,$2)',[R,'']));await denied(db.query('select mimo_publish_post($1,$2)',[R,'x'.repeat(2001)]));await denied(db.exec(`insert into posts(author_id,content,image_urls) values('${B}','image',array['https://bad.test'])`));
 });
 await t.test('Idempotent likes and comments expose own state and exact count strings',async()=>{
  await actor(A);await db.query('select mimo_plaza_like($1,true)',[T]);await db.query('select mimo_plaza_like($1,true)',[T]);await db.query('select mimo_comment_post($1,$2,$3)',[R,T,' hello ']);await db.query('select mimo_comment_post($1,$2,$3)',[R,T,'hello']);await denied(db.query('select mimo_comment_post($1,$2,$3)',[R,T,'changed']));const row=(await db.query('select * from mimo_plaza_feed()')).rows[0];assert.equal(row.likes,'1');assert.equal(row.comments,'1');assert.equal(row.liked,true);assert.equal((await db.query('select * from mimo_plaza_comments($1)',[T])).rows[0].content,'hello');await db.query('select mimo_plaza_like($1,false)',[T]);await db.query('select mimo_plaza_like($1,false)',[T]);assert.equal((await db.query('select * from mimo_plaza_feed()')).rows[0].likes,'0');
 });
 await t.test('Clients cannot change author/comment identity, forge timestamps or destroy other content',async()=>{
  await actor(A);await denied(db.exec(`update post_comments set post_id='${R}' where id='${R}'`));await denied(db.exec(`update post_comments set user_id='${B}' where id='${R}'`));await denied(db.exec(`insert into post_likes(post_id,user_id) values('${T}','${B}')`));await denied(db.exec(`insert into post_comments(post_id,user_id,content) values('${T}','${B}','forged')`));await denied(db.exec(`update post_comments set content=repeat('x',1001) where id='${R}'`));assert.equal((await db.query(`delete from posts where id='${T}' returning id`)).rows.length,0);
  await actor(B);await denied(db.exec(`update posts set author_id='${C}' where id='${T}'`));await denied(db.exec(`update posts set image_urls=array['https://bad.test'] where id='${T}'`));await denied(db.exec('truncate posts'));await denied(db.exec('truncate post_comments'));await denied(db.exec('update post_likes set created_at=now()'));await denied(db.exec(`update posts set created_at='2000-01-01' where id='${T}'`));
 });
 await t.test('Either-direction blocks hide posts and stop likes/comments; own removals remain possible',async()=>{
  await actor(B);await db.exec(`insert into blocked_users values('${B}','${A}')`);await actor(A);assert.equal((await db.query('select * from mimo_plaza_feed()')).rows.length,0);await denied(db.query('select mimo_plaza_like($1,true)',[T]));await denied(db.query('select mimo_comment_post($1,$2,$3)',['60000000-0000-4000-8000-000000000006',T,'blocked']));assert.equal((await db.query(`update post_comments set content='edit' where id='${R}' returning id`)).rows.length,0);assert.equal((await db.query(`delete from post_comments where id='${R}' returning id`)).rows.length,1);await actor(B);await db.exec(`delete from blocked_users`);await actor(A);await db.exec(`insert into blocked_users values('${A}','${B}')`);assert.equal((await db.query('select * from mimo_plaza_feed()')).rows.length,0);await db.exec('delete from blocked_users');assert.equal((await db.query('select * from mimo_plaza_feed()')).rows.length,1);
 });
 await t.test('Blocked commenter is hidden from others; comments paginate and posts delete own with children',async()=>{
  await actor(C);const id='70000000-0000-4000-8000-000000000007';await db.query('select mimo_comment_post($1,$2,$3)',[id,T,'C comment']);await actor(A);await db.exec(`insert into blocked_users values('${A}','${C}')`);assert.equal((await db.query('select * from mimo_plaza_comments($1)',[T])).rows.length,0);await db.exec('delete from blocked_users');assert.equal((await db.query('select * from mimo_plaza_comments($1,1,0)',[T])).rows.length,1);assert.equal((await db.query('select * from mimo_plaza_comments($1,1,1)',[T])).rows.length,0);await actor(B);await db.exec(`delete from posts where id='${T}'`);assert.equal((await db.query('select count(*) n from post_comments')).rows[0].n,0);
 });
 await t.test('Anon EXECUTE/read denied; no-UID feed empty; rollback preserves remaining rows',async()=>{
  await actor('','anon');await denied(db.query('select * from mimo_plaza_feed()'));await denied(db.query('select * from posts'));await actor('');assert.equal((await db.query('select * from mimo_plaza_feed()')).rows.length,0);await denied(db.query('select mimo_publish_post($1,$2)',[T,'hello']));await actor(B);await db.query('select mimo_publish_post($1,$2)',[T,'Restored']);await db.exec('reset role');await db.exec(fs.readFileSync(root+'/database/rollback-plaza.sql','utf8'));assert.equal((await db.query('select count(*) n from posts')).rows[0].n,1);await actor(A);await denied(db.exec('truncate posts'));
 });await db.close();
});
function helper(){const dom=new JSDOM('',{runScripts:'outside-only'});dom.window.eval(fs.readFileSync(root+'/plaza.js','utf8'));return {dom,api:dom.window.MimoPlaza};}
test('Plaza rendering treats names/content as text and permits only HTTPS existing images',()=>{const {dom,api}=helper(),d=dom.window.document;d.body.append(api.renderFeed(d,[{id:T,author_id:B,author_name:'<img>',content:'<script>bad</script>',image_urls:['javascript:bad','data:image/png,xx','https://images.test/one.png'],created_at:new Date(),likes:'1',comments:'0',liked:false}],A,{like(){},comments(){},remove(){}}));assert.equal(d.querySelectorAll('script').length,0);assert.equal(d.querySelectorAll('img').length,1);assert.equal(d.querySelector('a').getAttribute('href'),'profile.html?id='+B);assert.equal(d.querySelectorAll('button').length,2);assert.equal(api.imageURL('https://user:secret@test/'),null);dom.window.close();});
test('Plaza mutations validate input and distinguish stale removal/invalid like response',async()=>{const {dom,api}=helper();let calls=0;const client={rpc:async()=>{calls++;return {data:null};},from:()=>({delete(){return this;},eq(){return this;},select:async()=>({data:[]})})};await assert.rejects(api.publish(client,T,''));await assert.rejects(api.comment(client,T,R,'x'.repeat(1001)));assert.equal(calls,0);await assert.rejects(api.like(client,T,true),/unavailable/);await assert.rejects(api.remove(client,'posts',T,B),/changed/);dom.window.close();});
const turn=()=>new Promise(r=>setImmediate(r));
function page(client,api){const dom=new JSDOM(fs.readFileSync(root+'/plaza.html','utf8'),{runScripts:'outside-only',url:'https://mimo.test/plaza.html'});dom.window.supabase={createClient:()=>client};dom.window.MimoPlaza=api;dom.window.eval(Array.from(dom.window.document.scripts).find(s=>s.textContent.includes('async function init')).textContent);return dom;}
function authClient(uid){return {auth:{getUser:async()=>({data:{user:uid?{id:uid}:null}}),onAuthStateChange:()=>({data:{subscription:{unsubscribe(){}}}})}};}
test('Signed-out Plaza exposes login and User has no publishing controls',async()=>{let dom=page(authClient(null),{});await turn();assert.equal(dom.window.document.querySelector('#status a').getAttribute('href'),'login.html');assert.equal(dom.window.document.querySelector('#postFields').disabled,true);dom.window.close();dom=page(authClient(A),{role:async()=> 'user',feed:async()=>[],renderFeed:d=>d.createDocumentFragment()});await turn();assert.equal(dom.window.document.querySelector('#composer').hidden,true);assert.equal(dom.window.document.querySelector('#postFields').disabled,true);dom.window.dispatchEvent(new dom.window.Event('pagehide'));dom.window.close();});
test('Logout during Plaza read suppresses stale render and clears private drafts',async()=>{let auth,release;const client=authClient(A);client.auth.onAuthStateChange=fn=>{auth=fn;return {data:{subscription:{unsubscribe(){}}}};};const dom=page(client,{role:async()=> 'user',feed:()=>new Promise(r=>release=r),renderFeed(){throw Error('Stale render');}});await turn();dom.window.document.querySelector('#commentBody').value='private';auth('SIGNED_OUT',null);release([{id:T}]);await turn();assert.equal(dom.window.document.querySelector('#feed').children.length,0);assert.equal(dom.window.document.querySelector('#commentBody').value,'');assert.equal(dom.window.document.querySelector('#refresh').disabled,true);dom.window.close();});
test('Host publish retains text and request UUID across failed response retries',async()=>{const ids=[],api={role:async()=> 'host',feed:async()=>[],renderFeed:d=>d.createDocumentFragment(),clean:v=>v.trim(),publish:async(client,id)=>{ids.push(id);throw Error('Network');}};const dom=page(authClient(B),api);await turn();const d=dom.window.document;assert.equal(d.querySelector('#composer').hidden,false);d.querySelector('#postBody').value='hello';for(let i=0;i<2;i++){d.querySelector('#publish').dispatchEvent(new dom.window.Event('submit',{cancelable:true}));await turn();}assert.equal(ids.length,2);assert.equal(ids[0],ids[1]);assert.equal(d.querySelector('#postBody').value,'hello');dom.window.dispatchEvent(new dom.window.Event('pagehide'));dom.window.close();});
