const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),{JSDOM}=require('jsdom');const turn=()=>new Promise(r=>setImmediate(r));
const row={id:'40000000-0000-4000-8000-000000000004',author_id:'20000000-0000-4000-8000-000000000002',author_name:'Amy',content:'My Reel',video_url:'https://video.test/a.mp4',image_urls:[],created_at:'2026-10-11',likes:'0'};
function setup(fetchPage){const dom=new JSDOM(fs.readFileSync('plaza.html','utf8'),{runScripts:'outside-only',pretendToBeVisual:true}),w=dom.window,d=w.document,observers=[];let owner='user';w.HTMLMediaElement.prototype.pause=function(){this.stopped=true;};w.HTMLMediaElement.prototype.load=()=>{};w.HTMLMediaElement.prototype.play=()=>Promise.resolve();w.IntersectionObserver=class{constructor(cb,options){observers.push({cb,options});}observe(){}unobserve(){}disconnect(){}};for(const f of ['plaza.js','reel-playback.js','reels-viewer.js'])w.eval(fs.readFileSync(f,'utf8'));const dialog=d.querySelector('#reelsViewer'),stream=d.querySelector('#reelsStream'),tabs=d.querySelectorAll('[data-reels-mode]'),api=w.MimoReelsViewer.create({dialog,stream,status:d.querySelector('#reelsStatus'),more:d.querySelector('#reelsMore'),closeButton:d.querySelector('#reelsClose'),tabs,getUser:()=>owner,fetchPage,getHandlers:()=>({like(){},comments(){}})});return {dom,w,d,dialog,stream,tabs,api,observers,expire(){owner=null;}};}
test('Immersive opening carries time/sound, uses scrolling observer root, retains player on interactions and releases on close',async()=>{const t=setup(async()=>[row]);t.api.open(row,{currentTime:19,muted:false});await turn();const video=t.stream.querySelector('video');assert.equal(t.observers[0].options.root,t.stream);t.observers[0].cb([{target:video,isIntersecting:true,intersectionRatio:1}]);video.dispatchEvent(new t.w.Event('loadedmetadata'));assert.equal(video.currentTime,19);assert.equal(video.muted,false);t.api.refresh([{...row,liked:true,likes:'1'}]);assert.equal(t.stream.querySelector('video'),video);assert.equal(video.currentTime,19);assert.equal(video.muted,false);t.api.close();assert.equal(t.stream.children.length,0);assert.equal(t.api.isOpen(),false);assert.equal(video.hasAttribute('src'),false);assert.equal(t.d.documentElement.style.overflow,'');t.api.dispose();t.dom.window.close();});
test('Following switches query, clears Discover rows and rejects its late result; failure can retry',async()=>{let release,calls=[],fail=true;const t=setup((offset,mode)=>{calls.push({offset,mode});if(mode==='all')return new Promise(r=>release=r);return fail?Promise.reject(Error('offline')):Promise.resolve([]);});t.api.open(row);t.tabs[1].click();await turn();release([row]);await turn();assert.equal(t.stream.children.length,0);assert.equal(calls.at(-1).mode,'following');assert.match(t.d.querySelector('#reelsStatus').textContent,/Retry/);fail=false;await t.d.querySelector('#reelsMore').onclick();assert.match(t.d.querySelector('#reelsStatus').textContent,/Follow hosts/);assert.equal(t.stream.children.length,0);t.api.dispose();t.dom.window.close();});
test('Near-bottom scroll fetches next page and deduplicates; close/logout suppress late private rows',async()=>{let release,calls=[];const page=Array.from({length:20},(_,i)=>({...row,id:String(i)}));const t=setup((offset,mode)=>{calls.push(offset);return offset?new Promise(r=>release=r):Promise.resolve(page);});t.api.open(row);await turn();assert.equal(t.stream.children.length,21);Object.defineProperty(t.stream,'clientHeight',{value:600});Object.defineProperty(t.stream,'scrollHeight',{value:1000});t.stream.scrollTop=500;t.stream.dispatchEvent(new t.w.Event('scroll'));assert.equal(calls.at(-1),20);t.expire();t.api.close();release([{...row,content:'private'}]);await turn();assert.equal(t.stream.children.length,0);assert.equal(t.dialog.hasAttribute('open'),false);t.api.dispose();t.dom.window.close();});
test('Outer picture opens viewer while separate sound button only toggles audio',()=>{const t=setup(async()=>[]);let opened=0;const feed=t.d.querySelector('#feed');feed.append(t.w.MimoPlaza.renderFeed(t.d,[row],'user',{like(){},comments(){}}));const api=t.w.MimoReelPlayback.create(feed,()=>true,()=>false,{onOpen:()=>opened++}),video=feed.querySelector('video');t.observers[0].cb([{target:video,isIntersecting:true,intersectionRatio:1}]);feed.querySelector('.reel-sound').click();assert.equal(video.muted,false);assert.equal(opened,0);video.click();assert.equal(opened,1);api.dispose();t.api.dispose();t.dom.window.close();});

test('Blocked author DOM removal cannot be recreated by subsequent feed refresh',async()=>{const t=setup(async()=>[row]);t.api.open(row);await turn();t.stream.querySelector('article').remove();t.api.refresh([]);assert.equal(t.stream.children.length,0);t.api.dispose();t.dom.window.close();});
