const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {PGlite}=require('@electric-sql/pglite'),{JSDOM}=require('jsdom'),root=path.join(__dirname,'..');
const A='10000000-0000-4000-8000-000000000001',B='20000000-0000-4000-8000-000000000002',C='30000000-0000-4000-8000-000000000003',T='40000000-0000-4000-8000-000000000004',R='50000000-0000-4000-8000-000000000005';
test('Support lifecycle respects ownership/admin authority, atomic creation and retry',async t=>{
 const db=new PGlite();await db.exec(fs.readFileSync(__dirname+'/contact-policy-fixture.sql','utf8'));await db.exec(fs.readFileSync(root+'/supabase/migrations/20261009233713_mimo_contact_permissions.sql','utf8'));
 await db.exec(`create function public.is_admin(uid uuid) returns boolean language sql stable security definer set search_path=public as $$select exists(select 1 from profiles where id=uid and role='admin')$$;
 create table support_tickets(id uuid default gen_random_uuid() primary key,user_id uuid not null references profiles(id),subject text not null,category text not null default 'general' check(category in ('general','account','payment','diamond','vip','withdrawal','host','report','technical','other')),priority text not null default 'normal' check(priority in ('low','normal','high','urgent')),status text not null default 'open' check(status in ('open','in_progress','resolved','closed')),created_at timestamptz not null default now(),updated_at timestamptz not null default now());
 create table support_messages(id uuid default gen_random_uuid() primary key,ticket_id uuid not null references support_tickets(id),sender_id uuid not null references profiles(id),message text not null,attachment_url text,created_at timestamptz not null default now());
 alter table support_tickets enable row level security;alter table support_messages enable row level security;grant all on support_tickets,support_messages to authenticated,anon;
 create policy support_tickets_user_read on support_tickets for select to authenticated using(user_id=auth.uid() or is_admin(auth.uid()));
 create policy support_tickets_user_insert on support_tickets for insert to authenticated with check(user_id=auth.uid());
 create policy support_tickets_user_update on support_tickets for update to authenticated using(user_id=auth.uid() or is_admin(auth.uid())) with check(user_id=auth.uid() or is_admin(auth.uid()));
 create policy support_messages_read on support_messages for select to authenticated using(exists(select 1 from support_tickets t where t.id=ticket_id and (t.user_id=auth.uid() or is_admin(auth.uid()))));
 create policy support_messages_insert on support_messages for insert to authenticated with check(sender_id=auth.uid() and exists(select 1 from support_tickets t where t.id=ticket_id and (t.user_id=auth.uid() or is_admin(auth.uid()))));
 insert into profiles(id,role) values('${A}','user'),('${B}','admin'),('${C}','host');`);
 await db.exec(fs.readFileSync(root+'/supabase/migrations/20261010140000_mimo_support_center.sql','utf8'));
 const actor=async(id,role='authenticated')=>{await db.exec('reset role');await db.query("select set_config('request.jwt.claim.sub',$1,false)",[id]);await db.exec('set role '+role);};
 const denied=promise=>assert.rejects(promise,e=>e.code==='42501');
 await t.test('Create is atomic, trimmed and retry-safe; changed replay rejects',async()=>{
  await actor(A);await denied(db.query('select mimo_open_support($1,$2,$3,$4)',[R,'Question','general','']));assert.equal((await db.query('select count(*) n from support_tickets')).rows[0].n,0);
  await db.query('select mimo_open_support($1,$2,$3,$4)',[T,' Question ','technical',' Hello ']);await db.query('select mimo_open_support($1,$2,$3,$4)',[T,'Question','technical','Hello']);assert.equal((await db.query('select count(*) n from support_messages')).rows[0].n,1);
  await denied(db.query('select mimo_open_support($1,$2,$3,$4)',[T,'Changed','technical','Hello']));await denied(db.query('select mimo_open_support($1,$2,$3,$4)',[R,'x'.repeat(121),'general','Hello']));
 });
 await t.test('Other users cannot read, reply, close or reuse a ticket ID',async()=>{
  await actor(C);assert.equal((await db.query('select * from support_tickets')).rows.length,0);assert.equal((await db.query('select * from support_messages')).rows.length,0);await denied(db.query('select mimo_reply_support($1,$2,$3)',[R,T,'intruder']));assert.equal((await db.query('select mimo_support_transition($1,$2,$3)',[T,'open','closed'])).rows[0].mimo_support_transition,false);await denied(db.query('select mimo_open_support($1,$2,$3,$4)',[T,'Question','technical','Hello']));
 });
 await t.test('Clients cannot forge priority/status, owner, timestamps, attachments or staff messages',async()=>{
  await actor(A);await denied(db.exec(`insert into support_tickets(user_id,subject,status) values('${A}','fake','resolved')`));await denied(db.exec(`update support_tickets set priority='urgent' where id='${T}'`));await denied(db.exec(`update support_tickets set user_id='${C}' where id='${T}'`));await denied(db.exec(`update support_tickets set subject='new' where id='${T}'`));await denied(db.exec(`insert into support_messages(ticket_id,sender_id,message) values('${T}','${B}','fake staff')`));await denied(db.exec(`insert into support_messages(ticket_id,sender_id,message,attachment_url) values('${T}','${A}','x','https://bad.test')`));await denied(db.exec(`insert into support_messages(ticket_id,sender_id,message) values('${T}','${A}',repeat('x',4001))`));
  await db.exec(`insert into support_messages(id,ticket_id,sender_id,message,created_at) values('${R}','${T}','${A}','Timestamp','2000-01-01')`);assert.ok((await db.query(`select created_at from support_messages where id='${R}'`)).rows[0].created_at.getFullYear()>2000);
 });
 await t.test('Support replies are append-only; repeated matching response does not duplicate',async()=>{
  await actor(B);assert.equal((await db.query('select mimo_support_access()')).rows[0].mimo_support_access,true);assert.equal((await db.query('select * from support_tickets')).rows.length,1);await db.query('select mimo_support_transition($1,$2,$3,$4)',[T,'open','in_progress','high']);
  const id='60000000-0000-4000-8000-000000000006';await db.query('select mimo_reply_support($1,$2,$3)',[id,T,'Staff answer']);await db.query('select mimo_reply_support($1,$2,$3)',[id,T,'Staff answer']);await denied(db.query('select mimo_reply_support($1,$2,$3)',[id,T,'changed']));await denied(db.exec('update support_messages set message=\'forged\''));await denied(db.exec('delete from support_messages'));await denied(db.exec('truncate support_messages'));await denied(db.exec('truncate support_tickets'));
 });
 await t.test('Stale transitions fail; resolved replies stop; owner may close and nobody reopens',async()=>{
  await actor(B);assert.equal((await db.query('select mimo_support_transition($1,$2,$3)',[T,'open','resolved'])).rows[0].mimo_support_transition,false);await db.query('select mimo_support_transition($1,$2,$3)',[T,'in_progress','resolved']);await actor(A);await denied(db.query('select mimo_reply_support($1,$2,$3)',['70000000-0000-4000-8000-000000000007',T,'late']));await db.query('select mimo_support_transition($1,$2,$3)',[T,'resolved','closed']);await actor(B);await denied(db.query('select mimo_support_transition($1,$2,$3)',[T,'closed','in_progress']));await denied(db.exec(`delete from support_tickets where id='${T}'`));
 });
 await t.test('Anonymous cannot invoke APIs; no-UID gets no data; safe rollback retains history',async()=>{
  await actor('','anon');await denied(db.query('select mimo_support_access()'));await actor('');assert.equal((await db.query('select * from support_tickets')).rows.length,0);await denied(db.query('select mimo_open_support($1,$2,$3,$4)',[R,'Hello','general','body']));
  await db.exec('reset role');const before=(await db.query('select count(*) n from support_messages')).rows[0].n;await db.exec(fs.readFileSync(root+'/database/rollback-support-center.sql','utf8'));assert.equal((await db.query('select count(*) n from support_messages')).rows[0].n,before);await actor(A);await denied(db.exec('truncate support_tickets'));
 });await db.close();
});
function helper(){const dom=new JSDOM('',{runScripts:'outside-only'});dom.window.eval(fs.readFileSync(root+'/support-center.js','utf8'));return {dom,api:dom.window.MimoSupport};}
test('Support helpers validate text and category before sending; stale update is not success',async()=>{const {dom,api}=helper();let sent=0;const client={rpc:async()=>{sent++;return {data:false};}};await assert.rejects(api.open(client,T,'','general','hello'));await assert.rejects(api.open(client,T,'hello','invalid','hello'));assert.equal(sent,0);await assert.rejects(api.transition(client,{id:T,status:'open'},'closed'),/changed/);assert.throws(()=>api.clean('x'.repeat(4001),4000));dom.window.close();});
test('Support ticket and reply content render as text and distinguish requester/support',()=>{const {dom,api}=helper(),d=dom.window.document;d.body.append(api.renderTickets(d,[{id:T,subject:'<img onerror=bad>',category:'technical',status:'open',priority:'normal'}],()=>{}));d.body.append(api.renderMessages(d,[{sender_id:B,message:'<script>bad</script>',created_at:new Date()}],A,A));assert.equal(d.querySelector('img,script'),null);assert.ok(d.body.textContent.includes('Support'));dom.window.close();});
function page(client,api){const dom=new JSDOM(fs.readFileSync(root+'/support.html','utf8'),{runScripts:'outside-only',url:'https://mimo.test/support.html'});dom.window.supabase={createClient:()=>client};dom.window.MimoSupport=api;dom.window.eval(Array.from(dom.window.document.scripts).find(s=>s.textContent.includes('async function init')).textContent);return dom;}
const turn=()=>new Promise(r=>setImmediate(r));
test('Signed-out support page provides login and disables both submission forms',async()=>{const dom=page({auth:{getUser:async()=>({data:{user:null}}),onAuthStateChange:()=>({data:{subscription:{unsubscribe(){}}}})}},{});await turn();assert.equal(dom.window.document.querySelector('#status a').getAttribute('href'),'login.html');assert.equal(dom.window.document.querySelector('#newFields').disabled,true);assert.equal(dom.window.document.querySelector('#replyFields').disabled,true);dom.window.close();});
test('Logout during support load suppresses private results and clears drafts',async()=>{let auth,release;const dom=page({auth:{getUser:async()=>({data:{user:{id:A}}}),onAuthStateChange(fn){auth=fn;return {data:{subscription:{unsubscribe(){}}}};}}},{access:async()=>false,tickets:()=>new Promise(r=>release=r),renderTickets(){throw Error('Stale render');}});await turn();dom.window.document.querySelector('#body').value='private';auth('SIGNED_OUT',null);release([{id:T}]);await turn();assert.equal(dom.window.document.querySelector('#tickets').children.length,0);assert.equal(dom.window.document.querySelector('#body').value,'');assert.equal(dom.window.document.querySelector('#newFields').disabled,true);dom.window.close();});
test('Failed support submit keeps same request ID on retry and retains draft',async()=>{let count=0,ids=[];const api={access:async()=>false,tickets:async()=>[],renderTickets:d=>d.createDocumentFragment(),clean:v=>v.trim(),open:async(idclient,id)=>{ids.push(id);count++;throw Error('Network');}};const dom=page({auth:{getUser:async()=>({data:{user:{id:A}}}),onAuthStateChange:()=>({data:{subscription:{unsubscribe(){}}}})}},api);await turn();const d=dom.window.document;d.querySelector('#subject').value='hello';d.querySelector('#body').value='problem';for(let i=0;i<2;i++){d.querySelector('#create').dispatchEvent(new dom.window.Event('submit',{cancelable:true}));await turn();}assert.equal(count,2);assert.equal(ids[0],ids[1]);assert.equal(d.querySelector('#body').value,'problem');assert.equal(d.querySelector('#adminScope').hidden,true);dom.window.dispatchEvent(new dom.window.Event('pagehide'));dom.window.close();});
