begin;
do $$
declare a uuid:=gen_random_uuid(); b uuid:=gen_random_uuid(); c uuid:=gen_random_uuid(); chat uuid:=gen_random_uuid(); n integer;
begin
insert into auth.users(id,raw_user_meta_data) values(a,jsonb_build_object('username','notify_'||a::text)),(b,jsonb_build_object('username','notify_'||b::text)),(c,jsonb_build_object('username','notify_'||c::text));
update public.profiles set role='host' where id=b;
perform set_config('request.jwt.claim.sub',a::text,true);
perform set_config('request.jwt.claims',jsonb_build_object('sub',a,'role','authenticated')::text,true);
execute 'set local role authenticated';
insert into public.conversations(id,user_one_id,user_two_id) values(chat,a,b);
insert into public.messages(conversation_id,sender_id,content) values(chat,a,'Notification smoke');
insert into public.calls(caller_id,callee_id,call_type,status) values(a,b,'voice','ringing');
insert into public.follows(follower_id,following_id) values(a,b);
select count(*) into n from public.notifications where user_id=b;
if n<>0 then raise exception 'Sender saw recipient notifications'; end if;
execute 'reset role';
perform set_config('request.jwt.claim.sub',b::text,true);
perform set_config('request.jwt.claims',jsonb_build_object('sub',b,'role','authenticated')::text,true);
execute 'set local role authenticated';
select count(*) into n from public.notifications where user_id=b;
if n<>3 then raise exception 'Expected 3 notices, got %',n; end if;
update public.notifications set is_read=true where user_id=b;
begin update public.notifications set title='forged' where user_id=b; raise exception 'Content mutation unexpectedly allowed'; exception when insufficient_privilege then null; end;
begin insert into public.notifications(user_id,notification_type,title) values(b,'system','forged'); raise exception 'Notice forgery unexpectedly allowed'; exception when insufficient_privilege then null; end;
if has_table_privilege('authenticated','public.notifications','TRUNCATE') then raise exception 'Client can truncate notices'; end if;
insert into public.notification_settings(user_id,private_messages,calls,new_followers) values(b,false,false,false);
execute 'reset role';
perform set_config('request.jwt.claim.sub',a::text,true);
perform set_config('request.jwt.claims',jsonb_build_object('sub',a,'role','authenticated')::text,true);
execute 'set local role authenticated';
insert into public.messages(conversation_id,sender_id,content) values(chat,a,'Suppressed smoke');
insert into public.calls(caller_id,callee_id,call_type,status) values(a,b,'video','ringing');
delete from public.follows where follower_id=a and following_id=b;
insert into public.follows(follower_id,following_id) values(a,b);
execute 'reset role';
select count(*) into n from public.notifications where user_id=b;
if n<>3 then raise exception 'Disabled preferences did not suppress'; end if;
perform set_config('request.jwt.claim.sub',c::text,true);
perform set_config('request.jwt.claims',jsonb_build_object('sub',c,'role','authenticated')::text,true);
execute 'set local role authenticated';
select count(*) into n from public.notifications where user_id=b;
if n<>0 then raise exception 'Third-party leak'; end if;
update public.notifications set is_read=false where user_id=b;
get diagnostics n=row_count;
if n<>0 then raise exception 'Third-party acknowledgement allowed'; end if;
execute 'reset role';
if has_function_privilege('anon','mimo_private.emit_contact_notification()','EXECUTE') or has_function_privilege('authenticated','mimo_private.emit_contact_notification()','EXECUTE') then raise exception 'Public trigger execution'; end if;
end $$;
rollback;
select 'notification production smoke passed; all synthetic writes rolled back' as result;
